---
# Tsung Compile and Install
- name: create ssh config dir
  file:
    path=~/.ssh
    mode=700
    state=directory

- name: ssh keys
  template: 
    src=./roles/tsung/templates/id_rsa
    dest=~/.ssh/id_rsa
    mode=0600

- name: authorized_keys
  authorized_key:
    user="{{ ansible_ssh_user }}"
    key="{{ lookup('file', './roles/tsung/templates/id_rsa.pub') }}"

- name: ssh config
  template:
    src=./roles/tsung/templates/config
    dest=~/.ssh/config
    mode=0600

- name: install system packages for tsung compilation
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ tsung_yum_pkgs }}"

- name: clone the github repository
  git: >
    repo=https://github.com/processone/tsung.git
    dest={{ tsung_src_dir }}
    version={{ tsung_version }}

- name: configure
  shell:
    ./configure
    chdir={{ tsung_src_dir }}
    creates={{ tsung_src_dir }}/config.status

- name: make
  shell:
    /usr/bin/make
    chdir={{ tsung_src_dir }}
    creates={{ tsung_src_dir }}/ebin/tsung.app

- name: make install
  become: yes
  shell:
    /usr/bin/make install
    chdir={{ tsung_src_dir }}
