---
- name: Installing hosts file with IPs of all tsung boxes to communicate by hostname
  become: yes
  template: 
    src=./roles/hosts/templates/hosts.j2
    dest=/etc/hosts
    owner=root
    group=root
    mode=0644
